import { randomUUID } from 'node:crypto';
import { Injectable, NestMiddleware } from '@nestjs/common';
import type { NextFunction, Request, Response } from 'express';
import { CORRELATION_HEADER, runWithCorrelation } from './correlation';
import { MetricsService } from './metrics.service';

/**
 * Initializes the correlation AsyncLocalStorage for each request, ensuring that
 * logs, metrics, and spans within the same request share the same correlationId.
 * Also records the http_request_duration_seconds histogram on response finish.
 */
@Injectable()
export class CorrelationMiddleware implements NestMiddleware {
  constructor(private readonly metrics: MetricsService) {}

  use(req: Request, res: Response, next: NextFunction): void {
    // Aligns with the req.id generated by pino-http (which already reads the header or creates one),
    // ensuring the same correlationId in logs, metrics, and spans.
    const reqWithId = req as Request & { id?: string };
    const correlationId =
      reqWithId.id || (req.headers[CORRELATION_HEADER] as string) || randomUUID();
    // Persist on req.id so pino-http's genReqId reuses the same value (no divergence).
    reqWithId.id = correlationId;
    res.setHeader(CORRELATION_HEADER, correlationId);

    const start = process.hrtime.bigint();
    res.on('finish', () => {
      // Use the matched route PATTERN (e.g. /orders/:orderId/status), not the concrete URL,
      // to keep label cardinality bounded. Skip /metrics to avoid self-scrape noise.
      const matched = (req as Request & { route?: { path?: string } }).route?.path;
      const route = matched ? `${req.baseUrl ?? ''}${matched}` : 'unmatched';
      if (route === '/metrics') return;
      const seconds = Number(process.hrtime.bigint() - start) / 1e9;
      this.metrics.httpRequestDuration.observe(
        { method: req.method, route, status_code: String(res.statusCode) },
        seconds,
      );
    });

    runWithCorrelation({ correlationId }, () => next());
  }
}
