import { randomUUID } from 'node:crypto';
import { Injectable, NestMiddleware } from '@nestjs/common';
import type { NextFunction, Request, Response } from 'express';
import { CORRELATION_HEADER, runWithCorrelation } from './correlation';

/**
 * Initializes the correlation AsyncLocalStorage for each request, ensuring that
 * logs, metrics, and spans within the same request share the same correlationId.
 */
@Injectable()
export class CorrelationMiddleware implements NestMiddleware {
  use(req: Request, res: Response, next: NextFunction): void {
    // Aligns with the req.id generated by pino-http (which already reads the header or creates one),
    // ensuring the same correlationId in logs, metrics, and spans.
    const reqWithId = req as Request & { id?: string };
    const correlationId =
      reqWithId.id || (req.headers[CORRELATION_HEADER] as string) || randomUUID();
    // Persist on req.id so pino-http's genReqId reuses the same value (no divergence).
    reqWithId.id = correlationId;
    res.setHeader(CORRELATION_HEADER, correlationId);
    runWithCorrelation({ correlationId }, () => next());
  }
}
