import { Injectable, NestMiddleware } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import type { Request, Response, NextFunction } from 'express';
import { CORRELATION_HEADER, runWithCorrelation } from './correlation';

/**
 * Initializes the correlation AsyncLocalStorage for each request, ensuring that
 * logs, metrics, and spans within the same request share the same correlationId.
 */
@Injectable()
export class CorrelationMiddleware implements NestMiddleware {
  use(req: Request, res: Response, next: NextFunction): void {
    // Aligns with the req.id generated by pino-http (which already reads the header or creates one),
    // ensuring the same correlationId in logs, metrics, and spans.
    const fromPino = (req as Request & { id?: string }).id;
    const correlationId =
      fromPino || (req.headers[CORRELATION_HEADER] as string) || randomUUID();
    res.setHeader(CORRELATION_HEADER, correlationId);
    runWithCorrelation({ correlationId }, () => next());
  }
}
